import { color, border, shadow, radius, space, type } from '../theme'

export const safeArea = {
  top: { paddingTop: 'env(safe-area-inset-top)' },
  bottom: { paddingBottom: 'env(safe-area-inset-bottom)' },
  left: { paddingLeft: 'env(safe-area-inset-left)' },
  right: { paddingRight: 'env(safe-area-inset-right)' },
  horizontal: {
    paddingLeft: 'env(safe-area-inset-left)',
    paddingRight: 'env(safe-area-inset-right)',
  },
  all: {
    paddingTop: 'env(safe-area-inset-top)',
    paddingBottom: 'env(safe-area-inset-bottom)',
    paddingLeft: 'env(safe-area-inset-left)',
    paddingRight: 'env(safe-area-inset-right)',
  },
} as const

export const styles = {
  pageContainer: {
    padding: space.md,
    paddingBottom: space.xl,
  },
  topBar: {
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: `${space.sm}px ${space.sm}px ${space.xs}px`,
    gap: space.xs,
  },
  sectionTitle: {
    fontWeight: 800,
    fontSize: type.lg,
    color: color.text,
  },
  sectionSubtitle: {
    fontSize: type.sm,
    color: color.muted,
    fontWeight: 600,
    marginTop: 4,
  },
  keyPointBullet: {
    display: 'flex' as const,
    gap: space.lg,
    marginBottom: space.md,
  },
  keyPointDot: {
    width: 8,
    height: 8,
    background: color.secondary,
    border: `1px solid ${color.black}`,
    marginTop: 6,
    flexShrink: 0,
  },
  videoTabs: {
    display: 'flex' as const,
    gap: space.xs,
    overflowX: 'auto' as const,
    padding: `${10}px ${space.md}px ${4}px`,
    flexShrink: 0,
  },
  videoTab: {
    flexShrink: 0,
    display: 'flex' as const,
    alignItems: 'center',
    gap: 6,
    border: border.thin,
    borderRadius: radius.sm,
    boxShadow: shadow.sm,
    padding: '7px 12px',
    fontSize: type.xs,
    fontWeight: 800,
  },
  tabBar: {
    display: 'flex' as const,
    borderBottom: border.thin,
    marginTop: 6,
  },
  tabItem: {
    flex: 1,
    textAlign: 'center' as const,
    padding: '12px 0',
    fontWeight: 800,
    fontSize: type.xs,
  },
  contentArea: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: space.lg,
  },
  card: {
    padding: space.md,
    marginTop: space.lg,
    display: 'flex' as const,
    alignItems: 'center',
    gap: space.lg,
  },
  inputField: {
    background: color.card,
    border: border.thick,
    borderRadius: radius.md,
    boxShadow: shadow.sm,
    padding: '14px 16px',
    color: color.text,
    fontSize: type.md,
    outline: 'none',
  },
  levelCard: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: space.md,
    borderRadius: radius.md,
    padding: '16px 14px',
    marginBottom: space.xs,
  },
  checkIcon: {
    width: 22,
    height: 22,
    borderRadius: radius.sm,
    border: border.thin,
    background: color.secondary,
    color: '#fff',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    fontWeight: 900,
    flexShrink: 0,
  },
} as const
